package net.smartpager.android.consts;

public enum LoaderID {
	CONTACT_LOADER,
	MESSAGE_LOADER,
	ARCHIVE_MESSAGE_LOADER,
	CONTACT_EXISTS_LOADER,
	FORWARD_MESSAGE_LOADER,
	RECIPIENTS_LOADER,
	MESSAGE_IMAGE_LOADER,
	GROUP_LOADER,
	LOCAL_GROUP_CORRESPONDENCE_LOADER,
	RESPONSES_LOADER,
	UNREAD_MESSAGE_LOADER,
	RegistrGCM_Loader
}
