package net.smartpager.android.consts;

public enum RequestID {
	PICK_PHOTO,
	CROP_PHOTO,
	ADD_RECIPIENT,
	CHOOSE_QUICK_RESPONSE,
	CHOOSE_OPTIONS,
	ADD_VOICE_RECORD,
	EDIT_LOCAL_GROUP,
	MUTE_THREAD,
}
